version: '3'


services:
  app:
    build: ./
    command: ./stat4market
    ports:
      - "8080:8080"
    depends_on:
      - clickhouse-server
    environment:
      CLICKHOUSE_PASSWORD: secretPassword
      CLICKHOUSE_USER: secretUser

  clickhouse-server:
    restart: always
    image: clickhouse/clickhouse-server
    container_name: stat4market-container
    environment:
      CLICKHOUSE_USER: secretUser
      CLICKHOUSE_PASSWORD: secretPassword
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse:/var/lib/clickhouse
    ulimits:
      nofile: 26214
